### ISSUE TITLE
能否增加多测站数据管理及处理的功能

### ISSUE THREAD

**Issue by HLLF-FAN** [anyshake/observer#13]
在一个Observer上管理多个测站数据，并做相应处理

**Comment by bclswl0827** [comment]
AnyShake Observer is used one-to-one with AnyShake Explorer.
If you want to manage multiple stations, you need run multiple AnyShake Observer instances, and manage them with SeisComP through SeedLink.

**Comment by HLLF-FAN** [comment]
好的谢谢

**Comment by HLLF-FAN** [comment]
SeisComP该如何安装？

**Comment by bclswl0827** [comment]
See https://www.seiscomp.de/doc/base/tutorials/postinstall.html
If you find the tutorial too complicated, you can consider use other software, such as Swarm, SeisGram2K, jAmaSeis, etc. They also support importing multiple sites via SeedLink, but are more rudimentary.
