### ISSUE TITLE
使用Windows运行observer如何配置

### ISSUE THREAD

**Issue by HLLF-FAN** [anyshake/observer#16]
![image](https://github.com/user-attachments/assets/3de2288a-5441-4324-b2d2-4c7737008fb4)

**Comment by bclswl0827** [comment]
See [Explorer Settings - dsn](https://anyshake.org/docs/AnyShake%20Observer/Configuration/explorer#dsn) to configure your `explorer_settings`.
Here is a simple tutorial on how to find your serial port on Windows systems: [How to Find Your COM Port](https://wiki.analog.com/resources/eval/user-guides/inertial-mems/evalsystem/findyourcomport).
