### ISSUE TITLE
如果我想使用非AnyShake Explorer设备，链接AnyShake Observer，我应该以什么格式发送串口信息呢？

### ISSUE THREAD

**Issue by WhiteSong666** [anyshake/observer#3]
AnyShake Explorer使用的是ESP8266 + ADS1262，我想使用ESP32+ADS1256。我已经可以按100sps的采样率采集数据了，那么我应该如何编写串口发送函数，以输出AnyShake Observer能读取的数据呢？
简而言之，就是AnyShake Observer使用什么协议接收数据？

**Comment by bclswl0827** [comment]
The data packet is read in the following format:

```
| sync words (0xFC, 0x1B) | packet in struct |
```

Here are some snippets for your reference.

https://github.com/anyshake/explorer/blob/master/firmware/src/packet.cpp
https://github.com/anyshake/explorer/blob/master/firmware/include/packet.hpp#L10
https://github.com/anyshake/explorer/blob/master/firmware/src/main.cpp#L71
