### ISSUE TITLE
linux 系统下 config.json 文件到底放哪里？

### ISSUE THREAD

**Issue by strong-hub** [anyshake/observer#6]
![1](https://github.com/anyshake/observer/assets/9864787/ff404208-838b-493a-8457-1f14f945abde)
![2](https://github.com/anyshake/observer/assets/9864787/c5d7b932-117b-4969-91da-8d82a73322e3)

**Comment by bclswl0827** [comment]
Depends on observer.service, it should be ` /usr/local/etc/observer/config.json`, thanks for pointing out the typo.
