### ISSUE TITLE
Gap recorded MiniSEED and Real-Time seedlink 

### ISSUE THREAD

**Issue by PyaeAung** [anyshake/observer#7]
I am experiencing a noticeable gap in the recorded MiniSEED data and the real-time seedlink data. However, there is no gap in the history waveform. I am using the latest release of the software. Thanks 🙏 

<img width="1436" alt="Screenshot 2024-07-30 at 10 31 26 PM" src="https://github.com/user-attachments/assets/f7a96426-8053-45af-a5a0-8f98f30ea719">
<img width="1165" alt="Screenshot 2024-07-30 at 10 32 54 PM" src="https://github.com/user-attachments/assets/8f601f3d-f89e-417f-84c0-da2275bd1b25">

**Comment by TenkyuChimata** [comment]
Known issue, try [v2.12.1](https://github.com/anyshake/observer/releases/tag/v2.12.1)

**Comment by bclswl0827** [comment]
Hello, the gap issue has been resolved in v3.0.2, but there're some breaking changes and SeedLink service is temporarily unavailable. BTW, you may need to re-burn firmware of AnyShake Explorer.
See https://github.com/anyshake/observer/blob/master/CHANGELOG.md

**Comment by PyaeAung** [comment]
Thank you, I follow every step. But now I can't access the web-ui. 
I run on raspberry pi 4. Is there anything I need to add to config.json?

**observer.log** 
{"level":"info","module":"explorer","msg":"device is being initialized, please wait","time":"2024-08-09T21:08:09+08:00"}
{"level":"error","module":"explorer","msg":"failed to get device ID, please check the device","time":"2024-08-09T21:08:14+08:00"}
{"level":"info","module":"explorer","msg":"running cleaner task for explorer","time":"2024-08-09T21:08:14+08:00"}
{"level":"info","module":"explorer","msg":"closing connection to hardware device","time":"2024-08-09T21:08:14+08:00"}
{"level":"info","module":"database","msg":"running cleaner task for database","time":"2024-08-09T21:08:14+08:00"}
{"level":"info","module":"database","msg":"closing connection to database","time":"2024-08-09T21:08:14+08:00"}
{"level":"info","module":"main","msg":"global configuration has been loaded","time":"2024-08-09T21:08:19+08:00"}
{"level":"info","module":"main","msg":"querying NTP server at pool.ntp.org:123","time":"2024-08-09T21:08:19+08:00"}
{"level":"info","module":"main","msg":"time source has been created","time":"2024-08-09T21:08:19+08:00"}
{"level":"info","module":"main","msg":"database connection has been established","time":"2024-08-09T21:08:19+08:00"}
{"level":"info","module":"main","msg":"database schema has been migrated","time":"2024-08-09T21:08:19+08:00"}
{"level":"info","module":"explorer","msg":"device has been opened successfully","time":"2024-08-09T21:08:19+08:00"}
{"level":"info","module":"explorer","msg":"checking availability of opened device","time":"2024-08-09T21:08:19+08:00"}
{"level":"info","module":"explorer","msg":"device is being initialized, please wait","time":"2024-08-09T21:08:19+08:00"}

**Comment by bclswl0827** [comment]
> Thank you, I follow every step. But now I can't access the web-ui. I run on raspberry pi 4. Is there anything I need to add to config.json?
> 
> **observer.log** {"level":"info","module":"explorer","msg":"device is being initialized, please wait","time":"2024-08-09T21:08:09+08:00"} {"level":"error","module":"explorer","msg":"failed to get device ID, please check the device","time":"2024-08-09T21:08:14+08:00"} {"level":"info","module":"explorer","msg":"running cleaner task for explorer","time":"2024-08-09T21:08:14+08:00"} {"level":"info","module":"explorer","msg":"closing connection to hardware device","time":"2024-08-09T21:08:14+08:00"} {"level":"info","module":"database","msg":"running cleaner task for database","time":"2024-08-09T21:08:14+08:00"} {"level":"info","module":"database","msg":"closing connection to database","time":"2024-08-09T21:08:14+08:00"} {"level":"info","module":"main","msg":"global configuration has been loaded","time":"2024-08-09T21:08:19+08:00"} {"level":"info","module":"main","msg":"querying NTP server at pool.ntp.org:123","time":"2024-08-09T21:08:19+08:00"} {"level":"info","module":"main","msg":"time source has been created","time":"2024-08-09T21:08:19+08:00"} {"level":"info","module":"main","msg":"database connection has been established","time":"2024-08-09T21:08:19+08:00"} {"level":"info","module":"main","msg":"database schema has been migrated","time":"2024-08-09T21:08:19+08:00"} {"level":"info","module":"explorer","msg":"device has been opened successfully","time":"2024-08-09T21:08:19+08:00"} {"level":"info","module":"explorer","msg":"checking availability of opened device","time":"2024-08-09T21:08:19+08:00"} {"level":"info","module":"explorer","msg":"device is being initialized, please wait","time":"2024-08-09T21:08:19+08:00"}

Pleanse enable the `legacy` option in `explorer_settings` and try again.

**Comment by bclswl0827** [comment]
> SeedLink service is temporarily unavailable.

Update: SeedLink server is available again in [v3.1.0](https://github.com/anyshake/observer/releases/tag/v3.1.0), based on [github.com/bclswl0827/slgo](https://github.com/bclswl0827/slgo), a more stable implementation.
